//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BindingVideoClubAlvaro
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class videoclubEntities : DbContext
    {
        public videoclubEntities()
            : base("name=videoclubEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<alquileres> alquileres { get; set; }
        public DbSet<categorias> categorias { get; set; }
        public DbSet<estilos> estilos { get; set; }
        public DbSet<peliculas> peliculas { get; set; }
        public DbSet<socios> socios { get; set; }
    }
}
